  #插件名,不要重名
  name: EasyPvp

  api-version: 1.13
    #版本
  version: 1.2.1

  #主类的位置，插件开启时会调用这个类的相关方法
  main: pers.zhangyang.easypvp.EasyPvp

  #命令，建议只设置一个，然后其他的子命令通过第一个参数来区分
  commands:
    EasyPvp:
      aliases: ep

  #描述
  description: pvp plugin

  #作者
  author: ZhangYang

  softdepend:
    - PlaceholderAPI